# Site settings
title:              Wicle
description:        Compoment library for web front-end development.
repo:               "https://github.com/shnam7/wicle"
url:                "https://shnam7.github.io/wicle"
baseurl:            "/wicle"

# Project settings
# source and destination is set by gulpfile.js
#source:           .
# destination:        _site
version:            2.0.2
encoding:           utf-8
markdown:           kramdown
# highlighter:        none
permalink:          pretty
exclude:            ['_assets', 'Gemfile*', 'build.config.js', 'gulpfile.js', 'tsconfig.json']

# Module settings
kramdown:
  input: GFM
  auto_ids: false
  syntax_highlighter_opts:
    disable : true

#keep_files:       [css, js]

# Custom variable
