# Site settings
title:            Wicle
description:      Compoment library for web front-end development.
url:                "https://shnam7.github.io/wicle"
repo:               "https://github.com/shnam7/wicle"

# Project settings
# source and destination is set by gulpfile.js
#source:           .
# destination:        _site
version:            2.0.1
encoding:           utf-8
markdown:           kramdown
# highlighter:        none
permalink:          pretty
exclude:            ['_assets', 'Gemfile*', 'gbmconfig.js', 'gulpfile.js', 'tsconfig.json']
contentsurl:        wicle/contents

# Module settings
kramdown:
  input: GFM
  auto_ids: false
  syntax_highlighter_opts:
    disable : true

#keep_files:       [css, js]

# Custom variable
